### ISSUE TITLE
outdated link to mnist dataset

### ISSUE THREAD

**Issue by rasmuspjohansson** [skaae/rbm_toolbox_lua#3]
Hi,
After having problems with my own rbm implementation I was very happy to notice your code, and wanted to try out the examples.
Unfortunately the http://data.neuflow.org/data/mnist-th7.tgz link is broken and you dont seem to use the same format as the dataset in https://s3.amazonaws.com/torch7/data/mnist.t7.tgz

**Comment by yagizy** [comment]
Hi,

The dropbox link in the code https://www.dropbox.com/s/zdq98audyn8j845/mnist_lua.tar.gz?dl=0 and 
https://www.dropbox.com/s/1l9q60brgnssjde/mnist_lua.tar.gz?dl=0 both give 404.

Is there another adress I can use?

Best regards,
Yagiz

**Comment by skaae** [comment]
https://www.dropbox.com/s/zdq98audyn8j845/mnist_lua.tar.gz?dl=0     

I restored the file in my dropbox. Can you try again? 

best regards Søren

**Comment by yagizy** [comment]
Yes, I can download the dataset now. Thanks!

Best regards,
Yagiz

**Comment by yagizy** [comment]
I checked and the link works. Sorry, could not respond earlier...

## 

_Yagiz Yasaroglu_

Managing Partner
Mobilus Ltd.
Turkey
